=== cekahn/ROADMAP/old versions/draft-2025-01-06/Schema/ROADMAP.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "ROADMAP.json",
	"title": "Project",
	"description": "A Project is described by the Descriptor entities (Author, Date, Comments, etc.) and is comprised of zero or more Models and zero or more Datasets.",
	"$comment": "ROADMAP:00010",
	"type": "object",
	"properties": {
		"ROADMAP version": {
			"type": "string",
			"enum": ["2025-01-06"]
		},
		"Project": {
			"type": "object",
			"properties": {
				"Name": {"type": "string"},
				"Details": {"$ref": "ROADMAP.descriptor.json"}
			},
			"additionalProperties": false
		},
		"Model": {
			"description": "Descriptions of each Model",
			"type": "array",
			"items": {"$ref": "./ROADMAP.model.json"}
		},
		"Dataset": {
			"description": "Descriptions of each Dataset",
			"type": "array",
			"items": {"$ref": "./ROADMAP.dataset.json"}
		}
	},
	"required": [
		"ROADMAP version",
		"Project"
	],
	"additionalProperties": false
}

=== cekahn/ROADMAP/Schema/example-document.json
{
	"ROADMAP version": "2025-01-06",
	"Project": {
		"Name": "String",
		"Details": {
			"Content code": [
				"AI",
				"CT"
			],
			"RadLex code": [
				"RID0"
			],
			"Author": [
				{
					"Name": "String",
					"Email": "jdoe@example.com",
					"Address": "String",
					"ORCID": "https://orcid.org/0000-0000-0000-0000",
					"URL": "http://www.altova.com/"
				},
				{
					"Name": "String",
					"Email": "jdoe@example.com",
					"Address": "String",
					"ORCID": "https://orcid.org/0000-0000-0000-0000",
					"URL": "http://www.altova.com/"
				}
			],
			"Contributor": [
				{
					"Name": "String",
					"Email": "jdoe@example.com",
					"Address": "String",
					"ORCID": "https://orcid.org/0000-0000-0000-0000",
					"URL": "http://www.altova.com/"
				},
				{
					"Name": "String",
					"Email": "jdoe@example.com",
					"Address": "String",
					"ORCID": "https://orcid.org/0000-0000-0000-0000",
					"URL": "http://www.altova.com/"
				}
			],
			"Organization": [
				{
					"Name": "String",
					"Contact name": "String",
					"Email": "jdoe@example.com",
					"Address": "String",
					"URL": "http://www.altova.com/"
				},
				{
					"Name": "String",
					"Contact name": "String",
					"Email": "jdoe@example.com",
					"Address": "String",
					"URL": "http://www.altova.com/"
				}
			],
			"Date": {
				"Created": 2024,
				"Published": 2024,
				"Updated": 2024
			},
			"Version": "String",
			"Reference": [
				{
					"Authors": "Rudie JD, et al.",
					"Title": "The RSNA Abdominal Traumatic Injury CT (RATIC) Dataset",
					"Source": "Radiology: Artificial Intelligence",
					"Year": 2024,
					"DOI": "0 0/ ",
					"URL": "https://doi.org/10.1148/ryai.240101",
					"PMID": 39441109,
					"PMCID": "PMC8017407"
				},
				{
					"Authors": "Rudie JD, et al.",
					"Title": "The RSNA Abdominal Traumatic Injury CT (RATIC) Dataset",
					"Source": "Radiology: Artificial Intelligence",
					"Year": 2024,
					"DOI": "0 0/ ",
					"URL": "https://doi.org/10.1148/ryai.240101",
					"PMID": 39441109,
					"PMCID": "PMC8017407"
				}
			],
			"License": {
				"Text": "Non-commercial use",
				"URL": "https://creativecommons.org/licenses/by-nc-nd/4.0/"
			},
			"Contact": "String",
			"Funding": "String",
			"Ethical review": "String",
			"Comments": "String"
		}
	},
	"Model": [
		{
			"Name": "String",
			"Details": {
				"Content code": [
					"AI",
					"CT"
				],
				"RadLex code": [
					"RID0"
				],
				"Author": [
					{
						"Name": "String",
						"Email": "jdoe@example.com",
						"Address": "String",
						"ORCID": "https://orcid.org/0000-0000-0000-0000",
						"URL": "http://www.altova.com/"
					},
					{
						"Name": "String",
						"Email": "jdoe@example.com",
						"Address": "String",
						"ORCID": "https://orcid.org/0000-0000-0000-0000",
						"URL": "http://www.altova.com/"
					}
				],
				"Contributor": [
					{
						"Name": "String",
						"Email": "jdoe@example.com",
						"Address": "String",
						"ORCID": "https://orcid.org/0000-0000-0000-0000",
						"URL": "http://www.altova.com/"
					},
					{
						"Name": "String",
						"Email": "jdoe@example.com",
						"Address": "String",
						"ORCID": "https://orcid.org/0000-0000-0000-0000",
						"URL": "http://www.altova.com/"
					}
				],
				"Organization": [
					{
						"Name": "String",
						"Contact name": "String",
						"Email": "jdoe@example.com",
						"Address": "String",
						"URL": "http://www.altova.com/"
					},
					{
						"Name": "String",
						"Contact name": "String",
						"Email": "jdoe@example.com",
						"Address": "String",
						"URL": "http://www.altova.com/"
					}
				],
				"Date": {
					"Created": 2024,
					"Published": 2024,
					"Updated": 2024
				},
				"Version": "String",
				"Reference": [
					{
						"Authors": "Rudie JD, et al.",
						"Title": "The RSNA Abdominal Traumatic Injury CT (RATIC) Dataset",
						"Source": "Radiology: Artificial Intelligence",
						"Year": 2024,
						"DOI": "0 0/ ",
						"URL": "https://doi.org/10.1148/ryai.240101",
						"PMID": 39441109,
						"PMCID": "PMC8017407"
					},
					{
						"Authors": "Rudie JD, et al.",
						"Title": "The RSNA Abdominal Traumatic Injury CT (RATIC) Dataset",
						"Source": "Radiology: Artificial Intelligence",
						"Year": 2024,
						"DOI": "0 0/ ",
						"URL": "https://doi.org/10.1148/ryai.240101",
						"PMID": 39441109,
						"PMCID": "PMC8017407"
					}
				],
				"License": {
					"Text": "Non-commercial use",
					"URL": "https://creativecommons.org/licenses/by-nc-nd/4.0/"
				},
				"Contact": "String",
				"Funding": "String",
				"Ethical review": "String",
				"Comments": "String"
			},
			"Use": {
				"Intended": [
					"Artifact reduction",
					"Decision support"
				],
				"Out-of-scope": [
					"Artifact reduction",
					"Decision support"
				],
				"Excluded": [
					"Artifact reduction",
					"Decision support"
				]
			},
			"User": {
				"Intended": [
					"Administrator",
					"Advanced practice provider"
				],
				"Out-of-scope": [
					"Administrator",
					"Advanced practice provider"
				],
				"Excluded": [
					"Administrator",
					"Advanced practice provider"
				]
			},
			"Metric": [
				"Precision",
				"Recall"
			],
			"Caveat": "String",
			"Decision threshold": "String",
			"Ethical consideration": "String",
			"Recommendation": "String",
			"Availability": "String",
			"Sustainability": "String",
			"Time to train model": "String",
			"Time to evaluate single input": "String",
			"Required processor": "String",
			"Carbon footprint calculation": "String",
			"Method": [
				"https://paperswithcode.com/method/autoencoder",
				"https://paperswithcode.com/method/unet"
			],
			"Task": [
				"https://paperswithcode.com/task/object-detection",
				"https://paperswithcode.com/task/semantic-segmentation"
			]
		}
	],
	"Dataset": [
		{
			"Name": "String",
			"Details": {
				"Content code": [
					"AI",
					"CT"
				],
				"RadLex code": [
					"RID0"
				],
				"Author": [
					{
						"Name": "String",
						"Email": "jdoe@example.com",
						"Address": "String",
						"ORCID": "https://orcid.org/0000-0000-0000-0000",
						"URL": "http://www.altova.com/"
					},
					{
						"Name": "String",
						"Email": "jdoe@example.com",
						"Address": "String",
						"ORCID": "https://orcid.org/0000-0000-0000-0000",
						"URL": "http://www.altova.com/"
					}
				],
				"Contributor": [
					{
						"Name": "String",
						"Email": "jdoe@example.com",
						"Address": "String",
						"ORCID": "https://orcid.org/0000-0000-0000-0000",
						"URL": "http://www.altova.com/"
					},
					{
						"Name": "String",
						"Email": "jdoe@example.com",
						"Address": "String",
						"ORCID": "https://orcid.org/0000-0000-0000-0000",
						"URL": "http://www.altova.com/"
					}
				],
				"Organization": [
					{
						"Name": "String",
						"Contact name": "String",
						"Email": "jdoe@example.com",
						"Address": "String",
						"URL": "http://www.altova.com/"
					},
					{
						"Name": "String",
						"Contact name": "String",
						"Email": "jdoe@example.com",
						"Address": "String",
						"URL": "http://www.altova.com/"
					}
				],
				"Date": {
					"Created": 2024,
					"Published": 2024,
					"Updated": 2024
				},
				"Version": "String",
				"Reference": [
					{
						"Authors": "Rudie JD, et al.",
						"Title": "The RSNA Abdominal Traumatic Injury CT (RATIC) Dataset",
						"Source": "Radiology: Artificial Intelligence",
						"Year": 2024,
						"DOI": "0 0/ ",
						"URL": "https://doi.org/10.1148/ryai.240101",
						"PMID": 39441109,
						"PMCID": "PMC8017407"
					},
					{
						"Authors": "Rudie JD, et al.",
						"Title": "The RSNA Abdominal Traumatic Injury CT (RATIC) Dataset",
						"Source": "Radiology: Artificial Intelligence",
						"Year": 2024,
						"DOI": "0 0/ ",
						"URL": "https://doi.org/10.1148/ryai.240101",
						"PMID": 39441109,
						"PMCID": "PMC8017407"
					}
				],
				"License": {
					"Text": "Non-commercial use",
					"URL": "https://creativecommons.org/licenses/by-nc-nd/4.0/"
				},
				"Contact": "String",
				"Funding": "String",
				"Ethical review": "String",
				"Comments": "String"
			},
			"Imaging": {
				"Modality": [
					"3-Dimensional ultrasound (RID10920)",
					"3-Dimensional ultrasound (RID10920)"
				],
				"Procedure": [
					{
						"LOINC": "36623-7",
						"Name": "XR Hand - left PA"
					},
					{
						"LOINC": "36623-7",
						"Name": "XR Hand - left PA"
					}
				],
				"File format": [
					"DICOM",
					"DICOM"
				],
				"Resolution": "String",
				"Pre-processing": "String",
				"Burned-in PHI": "Yes"
			},
			"Labeling": "String",
			"Missing information": "String",
			"Relationships between instances": "String",
			"Noise": "String",
			"External data": "String",
			"Confidentiality": "String",
			"Subpopulations": "String",
			"Re-identification": "String",
			"Sensitive data": "String",
			"Collection process": "String",
			"Composition": {
				"Confidentiality": "String",
				"Number of instances": 1,
				"Representativeness": {
					"Population": "String",
					"Verification": "String"
				}
			},
			"Motivation": {
				"Purpose": "String",
				"Team": "String",
				"Funding": "String",
				"Comments": "String"
			},
			"Partioning scheme": "String",
			"Partition": {
				"Training": {
					"Sex": "Female",
					"Patient count": 501
				},
				"Optimization": {
					"Sex": "Female",
					"Patient count": 501
				},
				"Validation": {
					"Sex": "Female",
					"Patient count": 501
				},
				"Testing": {
					"Sex": "Female",
					"Patient count": 501
				},
				"Internal testing": {
					"Sex": "Female",
					"Patient count": 501
				},
				"External testing": {
					"Sex": "Female",
					"Patient count": 501
				}
			},
			"Subsets": [
				{
					"Sex": "Female",
					"Patient count": 501
				},
				{
					"Sex": "Female",
					"Patient count": 501
				}
			]
		}
	]
}
